language: go
sudo: required
services: docker
go:
- 1.7
install:
- go get ./...
- go get github.com/bradfitz/goimports
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
script:
- make
- "./.travis/build.sh && ./.travis/test.sh && ./.travis/publish.sh"
#- make coverage
#- "$HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.out"
deploy:
  provider: releases
  api_key:
    secure: SYx7JMfXLd2RxG8WL+Yxxsvk7YE+7+HnHiYWt15Z1vrVC3nm1lYbBC8Et2FnQQAhKiCPrFs0uT7PzC8RbRoHGODc4rFcWjsvp+tmNqJ7JS/4j6EV6dBkJlXSljWcAfuq+qFJgOp13ZTBOzTimCUNNihqnepaRmeo+eb5rK/Iy1TUDfPOOIMGSSdkpbehedDL83iip38MK+ofrVGGiCfCDVVhI4bnCgCf4ShDo1Ck2O8rBhrhBME/ky2nkIZFM+RUNqS52aGXH25DjIRBl4KRylKA1S2+z7NGVYaSXJtwRJx0iDyMgZhsc7Dt15L9/HluZQLk+x9NGkleITQ2ayAoffNdCQYDTPRp9oyYovbLQu5+T9JVty97UBuw74xosMpRwRQ/6w4Wjv1kqMo3jZZ4MvBtWna4ptHe+qRKXxsbfKqhWzL3DvJVBioOBI4N9qQWfFptabel9Y+ILucJzDRIIFMmebbmT9BZ4bpMHOCgGUj9mWmAkgH/QlD1xL6ObRp3VWKljhPM3Nm6WDJld1RSBloOdbCcCQXRQVgMVl/yFL1aVtBltrR1dlxQgBFlakL6dJeXgCJe3+cv86mC5G9M0X2AvwcH2mVeiUXKVytOaHhIAsAkXx+Zk48iPwkx1m+RqP3/F5D5L1s1LfDD3MvLilLTZWtFphWXr7ytQwUFYcY=
  file:
  - upkick
  - upkick.1
  on:
    repo: camptocamp/upkick
    tags: true
